### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by alejandrocibilich** [dynamiccast/sails-json-api-blueprints#37]
When lifting the app (sails v0.12, node v4.4.5), the console shows this error:

`SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

To make it work, had to use [strict-mode](https://www.npmjs.com/package/strict-mode) and modify `sails-json-api-blueprints\index.js` as:

`require('strict-mode')(function () {
    module.exports = require('./lib/hook.js');
});`

Is it there a more elegant way to solve this issue?

**Comment by dynamiccast** [comment]
Hi,

Thanks for your feedback. I wrote this module using ES6 features and node version 6.2.2. I did not realize it would be incompatible with node 4.
I can't think of a more elegant way to deal with this problem rather than either adding strict mode on top of every files or simply getting rid of used ES6 features.

Please not, Node 6 will go LTS on october 1th (https://github.com/nodejs/LTS). To me, the most elegant way to deal with issue would be to upgrade to node 6 if you can.
